version: "3"
services:
  syncmusic:
    build: .
    image: syncmusic
    ports:
      - "80:80"
      - "9501:9501"
    volumes:
      - .:/var/www
      - ./conf/syncmusic.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - redis
  redis:
    image: redis:alpine
